import { chromium } from 'playwright-core';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { existsSync } from 'node:fs';
import path from 'node:path';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const exe = ['C:/Program Files/Google/Chrome/Application/chrome.exe'].find(p => existsSync(p));
const b = await chromium.launch(exe ? { executablePath: exe } : { channel: 'chrome' });
const p = await b.newPage({ viewport: { width: +(process.argv[3]||1600), height: +(process.argv[4]||900) } });
await p.goto(pathToFileURL(path.join(ROOT, process.env.TPS_TARGET || 'v1-ruined.html')).href, { waitUntil: 'load' });
await p.waitForFunction(() => document.documentElement.classList.contains('sc-ready'), { timeout: 20000 });
await p.waitForTimeout(700);
await p.evaluate(() => { document.documentElement.style.scrollBehavior='auto';
  const a=document.querySelector('.act--voices');
  window.scrollTo(0, a.getBoundingClientRect().top + window.scrollY - 40); });
await p.waitForTimeout(1200);
const box = await p.locator('.act--voices').boundingBox();
await p.screenshot({ path: process.argv[2], clip: { x: box.x, y: Math.max(0,box.y), width: box.width, height: Math.min(box.height, 900 - Math.max(0,box.y)) } });
console.log('section', Math.round(box.height) + 'px');
await b.close();
