/* Emits the facts about this build that a machine can read, so no human has
   to keep them current and they cannot go stale.

   Everything here was previously typed by hand into HANDOVER.md and every one
   of those figures was wrong by 2026-09-16: the act table listed a section
   that does not exist, omitted one that does, and the git divergence counts
   described a state that had since been reconciled.

   Run it and paste the output, or write it to STATE.md:
     node lab/state.mjs
     node lab/state.mjs > STATE.md                                        */

import { chromium } from 'playwright-core';
import { pathToFileURL } from 'node:url';
import { execSync } from 'node:child_process';

const sh = c => { try { return execSync(c, { encoding: 'utf8' }).trim(); } catch { return ''; } };
const W = 1600, H = 900;

const b = await chromium.launch({ channel: 'chrome' });
const p = await b.newPage({ viewport: { width: W, height: H } });
await p.goto(pathToFileURL('v1.html').href);
await p.waitForLoadState('load');
await p.waitForTimeout(2500);

const doc = await p.evaluate(() => document.documentElement.scrollHeight);
const acts = await p.evaluate(() =>
  [...document.querySelectorAll('[data-section]')].map(el => {
    const r = el.getBoundingClientRect();
    return {
      name: el.dataset.section,
      cls: [...el.classList].find(c => c.startsWith('act--'))?.slice(5) ?? '',
      top: r.top + scrollY,
      h: r.height,
    };
  }));

/* Which section dominates the frame, sampled every tenth of a viewport. A
   section that never dominates is one you cannot point at, which is worth
   knowing before it is given a name. */
const owner = [];
for (let vh = 0; vh * H < doc - H; vh += 0.1) {
  await p.evaluate(y => scrollTo(0, y), vh * H);
  await p.waitForTimeout(40);
  owner.push(await p.evaluate(() => {
    const best = [...document.querySelectorAll('[data-section]')]
      .map(el => {
        const r = el.getBoundingClientRect();
        return { n: el.dataset.section, seen: Math.min(r.bottom, innerHeight) - Math.max(r.top, 0) };
      })
      .sort((a, b) => b.seen - a.seen)[0];
    return best.n;
  }));
}
await b.close();

const held = n => owner.filter(o => o === n).length / 10;
const trigs = sh('grep -c "ScrollTrigger.create\\|scrollTrigger:" v1.js');

console.log(`# Current state

Generated by \`lab/state.mjs\` on ${new Date().toISOString().slice(0, 10)} at ${W} by ${H}.
Do not edit this file. Regenerate it.

## Sections

${acts.length} in document order. "Holds" is how much of the scroll this section
is the largest thing on screen for, which is what the dev panel reports.

| n | name | class | top | height | holds |
|---|---|---|---|---|---|
${acts.map((a, i) =>
  `| ${i + 1} | \`${a.name}\` | \`act--${a.cls}\` | ${(a.top / H).toFixed(2)} | ${(a.h / H).toFixed(2)} | ${held(a.name).toFixed(1)} |`
).join('\n')}

Page is ${(doc / H).toFixed(2)} viewport heights. ${trigs} ScrollTriggers in \`v1.js\`.
${acts.filter(a => held(a.name) === 0).map(a => `\nNever dominates the frame: \`${a.name}\`. It cannot be pointed at by scrolling.`).join('')}

## Names

The class names are historical and several no longer describe what the section
holds. \`data-section\` is the identity. Use it in locks, commits and notes.
Numbers shift when a section is inserted; names do not.

## Repository

\`\`\`
${sh('git remote get-url origin')}   branch: ${sh('git rev-parse --abbrev-ref HEAD')}
\`\`\`

Against the last fetch, origin / local: ${sh('git rev-list --left-right --count origin/main...HEAD').replace(/\s+/, ' / ') || 'unknown'}
Modified: ${sh('git status --porcelain --untracked-files=no').split('\n').filter(Boolean).map(l => l.trim().split(/\s+/).pop()).join(', ') || 'nothing'}

Run \`git fetch origin\` first; the count above is only as fresh as the last one.

## Hero lock

${sh('node lab/herolock.mjs 2>&1 | tail -1') || 'not run'}
`);
